### ISSUE TITLE
게임의 큰 틀 정하기

### ISSUE THREAD

**Issue by sscc22** [Gifted-Children/Tree#1]
게임 장르와 방향성에 대한 토론

**Comment by enfycius** [comment]
나는 일단 RPG쪽 게임 개발을 해보고 싶고, [이런 식](https://www.pygame.org/project/596)의 게임 개발을 하면 어떨까 해

**Comment by sscc22** [comment]
횡스크롤 방식 좋아보이네요,  그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와  ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요

**Comment by enfycius** [comment]
> 횡스크롤 방식 좋아보이네요, 그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와 ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요

오 할로우 나이트에 RPG 요소를 넣는다면 좋을것 같아 !

**Comment by sscc22** [comment]
> > 횡스크롤 방식 좋아보이네요, 그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와 ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요
> 
> 오 할로우 나이트에 RPG 요소를 넣는다면 좋을것 같아 !
> 

로그라이크 형식은 어떻게 생각하시나요?

**Comment by enfycius** [comment]
> > > 횡스크롤 방식 좋아보이네요, 그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와 ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요
> > 
> > 
> > 오 할로우 나이트에 RPG 요소를 넣는다면 좋을것 같아 !
> 
> 로그라이크 형식은 어떻게 생각하시나요?

로그라이크 형식도 좋은것 같아 ! 로그라이크 형식의 게임에서는 세이브 기능이 빠지지?

**Comment by sscc22** [comment]
> > > > 횡스크롤 방식 좋아보이네요, 그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와 ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요
> > > 
> > > 
> > > 오 할로우 나이트에 RPG 요소를 넣는다면 좋을것 같아 !
> > 
> > 
> > 로그라이크 형식은 어떻게 생각하시나요?
> 
> 로그라이크 형식도 좋은것 같아 ! 로그라이크 형식의 게임에서는 세이브 기능이 빠지지?

네! 세이브 없이 사망하면 모든걸 잃고 처음부터 다시하는 것 입니다
하지만 던그리드 같이 플레이 할수록 조금씩 이점을 얻을 수 있는 요소를 넣을 수도 있죠
던그리드에 경우 지하에서npc를 찾아내어 마을을 키워서 이점을 얻는 방식을 사용하고있죠

**Comment by enfycius** [comment]
> > > > > 횡스크롤 방식 좋아보이네요, 그럼 ['메탈슬러그'](https://www.youtube.com/watch?v=y_D831mBAYg&ab_channel=sadeceKAAN) 같은 슈팅 요소와 ['할로우 나이트'](https://www.youtube.com/watch?v=SE7kje3z9c8&ab_channel=Gellot)같은 근접 전투 요소 중에서 어느것이 좋을까요
> > > > 
> > > > 
> > > > 오 할로우 나이트에 RPG 요소를 넣는다면 좋을것 같아 !
> > > 
> > > 
> > > 로그라이크 형식은 어떻게 생각하시나요?
> > 
> > 
> > 로그라이크 형식도 좋은것 같아 ! 로그라이크 형식의 게임에서는 세이브 기능이 빠지지?
> 
> 네! 세이브 없이 사망하면 모든걸 잃고 처음부터 다시하는 것 입니다
> 하지만 던그리드 같이 플레이 할수록 조금씩 이점을 얻을 수 있는 요소를 넣을 수도 있죠
> 던그리드에 경우 지하에서npc를 찾아내어 마을을 키워서 이점을 얻는 방식을 사용하고있죠

맹목적으로 로그라이크 형식만 따를 경우에 게임의 흥미 요소가 사라질 수 있는 부분을 고려하여 별도의 장치들을 마련했구나 ! 그러면 말한것처럼 게임 내의 게임이라는 아이디어를 이용하여 기존 로그라이크 형식 게임의 세이브 기능 부재로 인한 단점을 보완하면 좋을것 같아.
