### ISSUE TITLE
IDE 및 GIT Tutorial

### ISSUE THREAD

**Issue by enfycius** [Gifted-Children/Tree#3]
- IDE: Pycharm 사용
- [pycharm 깃 연동 작업 방법](../wiki/GIT-for-the-Tree-Project)

확인 바람.

**Comment by sscc22** [comment]
확인했습니다.  pycharm은 오픈소스로 다운했습니다.

**Comment by enfycius** [comment]
> 확인했습니다. pycharm은 오픈소스로 다운했습니다.

:+1::+1:
