### ISSUE TITLE
점프 구현 질문

### ISSUE THREAD

**Issue by sscc22** [Gifted-Children/Tree#4]
https://github.com/Gifted-Children/Tree/blob/dce257f8b1646003f19a2641f6bd0a89f5a843ec/game/game.py#L51-L52
개발 중 점프를 구현하는 데에 어려움을 겪고 있습니다

**Comment by enfycius** [comment]
@sscc22 
https://github.com/Gifted-Children/Tree/pull/5#issue-554299029
